Add ready for use RRule instance with caching
JonasWanke/rrule pull request #20
Opened 2021-04-21 10:23 UTC by polRk

Add RRule ready for use instance with result caching

### Checklist

- [  ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2021-04-21 10:25 UTC, polRk commented
I do not know how to cache `after` method without recurrence rule until value. Can u help me?

2021-04-21 10:27 UTC, polRk commented
I'm inspired by this repository https://github.com/jakubroztocil/rrule

2021-04-21 10:44 UTC, polRk commented on lib/src/rrule.dart
> +    final argumentsHash = hashList([instances, date, inc]);
Maybe it can be better?

```suggestion
    final argumentsHash = hashList([rule, start, date, inc]);
```

2021-04-26 10:07 UTC, JonasWanke commented
Thanks for this contribution! Caching seems like a really useful feature as the internal calculations in this package can get quite complex.

I have a few questions/comments/suggestions about the architecture of this caching:

* Having a class called `RRule` (the common abbreviation for Recurrence Rule) next to the class `RecurrenceRule` seems a bit confusing. Could we either integrate this functionality directly in `RecurrenceRule` or maybe rename `RRule` to `CachingRecurrenceRule`?
* rrule.js's `before` and `after` only return a single value (the first event before/after the given instant) as opposed to all values before/after that instant, but I think that the latter is useful as well. (And if we need the former in the future, we can still add methods calculating and returning only the single next event.) However, I'm not sure whether we really need three separate methods (`before`, `after`, and `between`). Maybe we can combine those into a single method with optional `before` and `after` parameters?

  ```dart
  List<DateTime> getAllInstances({
    required DateTime start, // Only necessary if this is integrated into `RecurrenceRule` directly.
    DateTime? after,
    bool includeAfter = false,
    DateTime? before,
    bool includeBefore = false,
  }) {/* ... */}
  ```

* Currently, a hash of all relevant parameters (rrule, start, and method arguments) is used as the cache key. While hash functions try to minimize the risk of collisions, those are not impossible. Hence, I recommend creating a utility class like `_CacheKey` which stores those arguments directly and, as the name suggests, is used as the cache key. And as the cache is currently stored per recurrence rule, the rrule doesn't even have to be part of this key.
* `RRule` accepts an `initialCache`, similar to rrule.js. Do you know of any use-cases for supplying that initial cache state, especially since the `cache` itself is not made public (and hence can't be persisted otherwise by users of this package)?

2021-04-26 12:45 UTC, polRk commented
> RRule accepts an initialCache, similar to rrule.js. Do you know of any use-cases for supplying that initial cache state, especially since the cache itself is not made public (and hence can't be persisted otherwise by users of this package)?

This can reduce the cold start. If I have 1000 recurring tasks, it will be better to use cached values rather than calculated ones.

2021-04-26 14:06 UTC, polRk commented on lib/src/recurrence_rule.dart
> +    this.shouldCacheResults = false,
Protection against unexpected memory leaks

2021-05-03 07:15 UTC, JonasWanke requested changes
This looks great! I've added some minor comments, and then this can get merged :)

2021-05-03 07:15 UTC, JonasWanke commented on lib/src/recurrence_rule.dart
> +
Please undo adding these empty lines

2021-05-03 07:15 UTC, JonasWanke commented on lib/src/cache.dart
> +  CacheKey({
```suggestion
@immutable
class CacheKey {
  const CacheKey({
```

2021-05-03 07:15 UTC, JonasWanke commented on lib/src/cache.dart
> +  bool includeBefore;
```suggestion
  final DateTime start;
  final DateTime? after;
  final bool includeAfter;
  final DateTime? before;
  final bool includeBefore;
```

2021-05-03 07:15 UTC, JonasWanke commented on lib/src/cache.dart
> +    _results.addAll({key: data});
```suggestion
    _results[key]= data;
```

2021-05-03 07:15 UTC, JonasWanke commented on test/cache_test.dart
> +  test('should return date from the cache by key', () {
```suggestion
  test('should return data from the cache by key', () {
```

2021-05-06 07:12 UTC, JonasWanke approved these changes

2021-05-06 07:12 UTC, merged

2021-05-06 07:19 UTC, JonasWanke commented
This is now published as part of [v0.2.3](https://pub.dev/packages/rrule/changelog#v023--2021-05-06). Thanks for contributing!