depreciate supercharged_dart
JonasWanke/rrule pull request #27
Opened 2021-12-30 18:19 UTC by thomassth

Since `supercharged_dart` stops development, and we don't need all of its arguments anyway, I've cleaned up the package with these methods:

- Replace with native arguments
- Replace with smaller, maintained packages (`time`)
- Copy only what we need from `supercharged_dart` and put it in (`until` and `rangeTo`, both stems from `Iterable.generate`)
>- These seems to be quite useful, and IMHO should be part of `collection`. But that's for another time.

Otherwise nothing changed.

All tests still passes.

2022-01-04 10:44 UTC, JonasWanke requested changes
Thanks a lot for this contribution!

I saw that you replaced `DateTime` arithmetic (`+`/`-`) with the native methods (`add`/`subtract`). Is there a specific reason for this, as [<kbd>time</kbd>](https://pub.dev/packages/time) contains `+`/`-` extensions? If not, could you please revert those specific changes?

2022-01-04 10:44 UTC, JonasWanke commented on lib/src/utils.dart
> +  ///Copied from supercharged_dart
Nit: Using a `///` adds this line to the doc comment of the next declaration, `rangeTo`.

```suggestion
  // Copied from supercharged_dart
```

2022-01-04 10:44 UTC, JonasWanke commented on lib/src/codecs/string/decoder.dart
> +                  until: DateTimeRrule(match).copyWith(isUtc: true));
Nit: Formatting

```suggestion
              return _UntilOrCount(
                until: DateTimeRrule(match).copyWith(isUtc: true),
              );
```

2022-01-04 20:16 UTC, JonasWanke commented
Could you please revert the replacement of operators (`+`/`-`) with the native methods (`add`/`subtract`) unless there's a reason to use these? I prefer operators because they're easier to read and more concise. When this is done, I'll merge and publish this.

FYI: For methods like `until` and `rangeTo`, there are open issues: dart-lang/collection#207, which you already discovered, and dart-lang/sdk#42652.

2022-01-04 20:49 UTC, thomassth commented
IMHO add/subtract are native solutions, does not make the code that much longer or hard to read, and means basically the same thing so not much rewrite was needed too.

+/- do look prettier, but they needs additional implementation, and potentially more effort on testing and debugging in the long run.

2022-01-05 10:20 UTC, JonasWanke approved these changes

2022-01-05 10:21 UTC, merged

2022-01-05 10:47 UTC, JonasWanke commented
This is now published as part of [v0.2.5](https://pub.dev/packages/rrule/changelog#025--2022-01-05). Thanks for contributing!