Support decoding valid json containing lists of type `List<dynamic>`
JonasWanke/rrule pull request #32
Opened 2022-04-29 17:59 UTC by nshoura

**Closes: #31**

Attempt to cast `List<dynamic>` to `List<T>` when parsing an RRule set.

### Checklist

- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

2022-05-04 07:29 UTC, JonasWanke requested changes
Thanks for the clear issue description and for creating a PR! I've only added two minor comments before this can get merged.

2022-05-04 07:29 UTC, JonasWanke commented on lib/src/codecs/json/decoder.dart
> +        throw FormatException('Invalid JSON in `$name`.');
```suggestion
      } catch(e, st) {
        throw FormatException('Invalid JSON in `$name`: $e\n\n$st');
```

2022-05-04 07:29 UTC, JonasWanke commented on test/codecs/json/json_test.dart
> +      'bymonth': [10],
```suggestion
      'bymonth': <dynamic>[10],
```

2022-05-04 12:58 UTC, nshoura commented
Thanks for the input @JonasWanke  :) Committed the proposed changes.

2022-05-05 06:52 UTC, JonasWanke approved these changes

2022-05-05 06:52 UTC, merged

2022-05-05 07:44 UTC, JonasWanke commented
Thanks for the quick changes! This PR is now published as part of [v0.2.8](https://pub.dev/packages/rrule/changelog#028--2022-05-05). Thanks for contributing!