Make RruleL10n.weekdaysString nullable and pass Frequency to RruleL10n.until
JonasWanke/rrule pull request #56
Opened 2023-05-25 13:50 UTC by absar

Closes: #54

* Make RruleL10n.weekdaysString nullable to simplify week days only if this is not null, since in some languages there is no word for weekdays or feels weird.
* Pass Frequency to RruleL10n.until to be able to format the date differently based on frequency.

2023-05-30 07:13 UTC, JonasWanke requested changes
The changes look good. However, I'm not sure whether the current localization strategy itself makes sense and is flexible enough to support other locales. Before releasing this breaking change, I'd like at least another localization (preferably multiple) to see whether the current strategy works. If I find the time, I can add a German localization, but I'm not proficient enough to add localizations for other locales.

2023-05-30 20:06 UTC, absar commented on lib/src/codecs/text/encoder.dart
> +        l10n.weekdaysString != '' &&
Removed blank check

2023-05-30 20:14 UTC, absar commented on lib/src/codecs/text/encoder.dart
> +      output.write(l10n.until(input.until!, input.frequency));
It is mostly to hide weekday for longer periods/frequencies for better UI and less verbosity, example if its a yearly interval users do not care on which day the recurrences will end they are just interested in date, hence we don't want to show weekday if period is more than 3 months

2023-06-02 07:51 UTC, JonasWanke approved these changes

2023-06-02 07:55 UTC, merged